# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e062b2afbda40feef1c957b971c7b292"
name = "only-caps"
handle = "only-caps"
application_url = "https://hydrocodone-family-criticism-year.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dummy-store-usa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hydrocodone-family-criticism-year.trycloudflare.com/auth/callback",
  "https://hydrocodone-family-criticism-year.trycloudflare.com/auth/shopify/callback",
  "https://hydrocodone-family-criticism-year.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
