# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e062b2afbda40feef1c957b971c7b292"
name = "Only Caps"
handle = "only-caps"
application_url = "https://only-caps-prod-7ec944292734.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dummy-store-usa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://only-caps-prod-7ec944292734.herokuapp.com/auth/callback",
  "https://only-caps-prod-7ec944292734.herokuapp.com/auth/shopify/callback",
  "https://only-caps-prod-7ec944292734.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://us-central1-only-caps.cloudfunctions.net/gdpr/redact/customer"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-only-caps.cloudfunctions.net/gdpr/redact/store"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-only-caps.cloudfunctions.net/gdpr/request/customer"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
